In [35]:
import pandas as pd

In [36]:
prefix = 'https://d37ci6vzurychx.cloudfront.net/trip-data'
url = f'{prefix}/green_tripdata_2025-11.parquet'

In [37]:
df = pd.read_parquet(url)

In [22]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.0

In [23]:
df.dtypes

VendorID                          int32
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag               object
RatecodeID                      float64
PULocationID                      int32
DOLocationID                      int32
passenger_count                 float64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                    float64
trip_type                       float64
congestion_surcharge            float64
cbd_congestion_fee              float64
dtype: object

In [38]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "lpep_pickup_datetime",
    "lpep_dropoff_datetime"
]

# Read parquet file
df = pd.read_parquet(url)

# Convert datetime columns
for col in parse_dates:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col])

# Convert numeric columns to specified dtypes
for col, dt in dtype.items():
    if col in df.columns:
        df[col] = df[col].astype(dt)

In [25]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1,74,42,1,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1,1.0,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1,74,42,2,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2,1.0,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1,83,160,1,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1,1.0,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1,166,127,1,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1,1.0,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1,166,262,1,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1,1.0,2.75,0.0

In [26]:
df.shape

(46912, 21)

In [27]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1,74,42,1,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1,1.0,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1,74,42,2,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2,1.0,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1,83,160,1,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1,1.0,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1,166,127,1,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1,1.0,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1,166,262,1,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1,1.0,2.75,0.0

In [39]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [40]:
print(pd.io.sql.get_schema(df, name='green_taxi_data', con=engine))

CREATE TABLE green_taxi_data (
	"VendorID" BIGINT,
	lpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	lpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	store_and_fwd_flag TEXT,
	"RatecodeID" BIGINT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	ehail_fee FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	payment_type BIGINT,
	trip_type FLOAT(53),
	congestion_surcharge FLOAT(53),
	cbd_congestion_fee FLOAT(53)
)

In [41]:
df.head(n=0).to_sql(name='green_taxi_data', con=engine, if_exists='replace')

0

In [31]:
len(df)

46912

In [42]:
import pyarrow.parquet as pq

def chunked_parquet_reader(url, batch_size=100000):
    """Read parquet file in chunks and apply dtype conversions"""
    parquet_file = pq.ParquetFile(url)
    
    for batch in parquet_file.iter_batches(batch_size=batch_size):
        df_chunk = batch.to_pandas()
        
        # Convert datetime columns
        for col in parse_dates:
            if col in df_chunk.columns:
                df_chunk[col] = pd.to_datetime(df_chunk[col])
        
        # Convert numeric columns to specified dtypes
        for col, dt in dtype.items():
            if col in df_chunk.columns:
                df_chunk[col] = df_chunk[col].astype(dt)
        
        yield df_chunk

# Create iterator
df_iter = chunked_parquet_reader(url, batch_size=10000)

In [43]:
df_iter

In [46]:
for df in df_iter:
    print(len(df))

10000
10000
10000
10000
6912

In [91]:
#for df in df_iter:
 #   df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

In [ ]:
# Fixed chunked reader with requests support
import requests
from io import BytesIO

def chunked_parquet_reader_fixed(url, batch_size=100000):
    """Read parquet file from URL in chunks"""
    response = requests.get(url)
    response.raise_for_status()
    parquet_file = pq.ParquetFile(BytesIO(response.content))
    
    for batch in parquet_file.iter_batches(batch_size=batch_size):
        df_chunk = batch.to_pandas()
        for col in parse_dates:
            if col in df_chunk.columns:
                df_chunk[col] = pd.to_datetime(df_chunk[col])
        for col, dt in dtype.items():
            if col in df_chunk.columns:
                df_chunk[col] = df_chunk[col].astype(dt)
        yield df_chunk

df_iter = chunked_parquet_reader_fixed(url, batch_size=10000)

In [134]:
!uv pip install tqdm
!uv add tqdm
!uv pip install ipywidgets

Audited 1 package in 1ms

In [47]:

from tqdm.auto import tqdm

In [48]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='green_taxi_data', con=engine, if_exists='append')

0it [00:00, ?it/s]

In [172]:
from tqdm.notebook import tqdm

for df_chunk in tqdm(df_iter, desc="Uploading chunks"):
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

Uploading chunks: 0it [00:00, ?it/s]

In [171]:
!uv pip install --python "{sys.executable}" ipywidgets

Audited 1 package in 4ms

In [170]:
!uv pip install --python "{sys.executable}" notebook

Audited 1 package in 64ms

In [193]:
# Simple tqdm test
from tqdm.auto import tqdm
import time  # just to slow down for visibility

# Loop 10 iterations with a progress bar
for i in tqdm(range(10), desc="Testing tqdm", ncols=80):
    time.sleep(0.2)  # sleep 0.2 seconds so you can see the bar updating

print("✅ tqdm is working!")

Testing tqdm:   0%|                                      | 0/10 [00:00<?, ?it/s]

✅ tqdm is working!